apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardware-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: hardware-service
  replicas: 1
  template:
    metadata:
      name: hardware-service
      labels:
        app: hardware-service
    spec:
      containers:
      - name: hardware-service
        env:
        - name: ENV_SERVER_EUREKA
          value: 'http://discovery-service:8761/eureka'
        - name: ENV_SERVER_DB
          value: 'jdbc:postgresql://postgres:5432/postgresdb'
        - name: ENV_USER_DB
          value: 'postgresadmin'
        - name: ENV_PASSWD_DB
          value: 'admin123'
        image: rizkinu/hardware-service:1.8